#!/bin/bash

# Skip everything
if [ -n "" ]; then

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

ARCH=${ARCH:-"amd64"}
TAG=${TAG:-"${VERSION}-${ARCH}"}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

fi

TAG=poc
REPO=rancher
VERSION=poc
ARCH=amd64
